# Generated by Django 3.2.4 on 2022-07-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(default=0, null=True, verbose_name='性别'),
        ),
    ]
