# Generated by Django 3.2.4 on 2022-07-19 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('path', models.CharField(max_length=40, null=True, verbose_name='跳转路径')),
                ('description', models.CharField(max_length=40, null=True, verbose_name='描述')),
                ('createTime', models.DateTimeField(max_length=1, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(max_length=1, null=True, verbose_name='修改时间')),
                ('deleteTime', models.DateTimeField(max_length=1, null=True, verbose_name='删除时间')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('isDelete', models.IntegerField(default=0, null=True, verbose_name='删除状态')),
                ('isShow', models.IntegerField(default=0, null=True, verbose_name='显示状态')),
                ('create_by', models.CharField(max_length=20, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'banner表',
                'verbose_name_plural': 'banner表',
                'db_table': 'stack_index_banner',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=8, verbose_name='标题')),
                ('path', models.CharField(max_length=20, verbose_name='路由路径')),
                ('description', models.CharField(max_length=40, null=True, verbose_name='描述')),
                ('createTime', models.DateTimeField(max_length=1, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(max_length=1, null=True, verbose_name='修改时间')),
                ('deleteTime', models.DateTimeField(max_length=1, null=True, verbose_name='删除时间')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('isDelete', models.IntegerField(default=0, null=True, verbose_name='删除状态')),
                ('isShow', models.IntegerField(default=1, null=True, verbose_name='显示状态')),
                ('create_by', models.CharField(max_length=20, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '导航表',
                'verbose_name_plural': '导航表',
                'db_table': 'stack_index_nav',
            },
        ),
        migrations.CreateModel(
            name='UserDynamic',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=40, null=True, verbose_name='标题')),
                ('createTime', models.DateTimeField(max_length=0, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(max_length=0, null=True, verbose_name='修改时间')),
                ('deleteTime', models.DateTimeField(max_length=0, null=True, verbose_name='删除时间')),
                ('type', models.IntegerField(null=True, verbose_name='类型')),
                ('dy_type', models.IntegerField(null=True, verbose_name='动态类型')),
                ('status', models.IntegerField(default=1, null=True, verbose_name='用户状态')),
                ('isDelete', models.IntegerField(default=0, null=True, verbose_name='删除状态')),
                ('isShow', models.IntegerField(default=0, null=True, verbose_name='显示状态')),
                ('create_by', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.classify', verbose_name='文章分类id')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'stack_user_dynamic',
            },
        ),
    ]
