# Generated by Django 3.2.4 on 2021-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='isShow',
            field=models.IntegerField(default=1, null=True, verbose_name='显示状态'),
        ),
    ]
