# Generated by Django 3.2.4 on 2022-07-19 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=8, verbose_name='分类名称')),
                ('description', models.CharField(max_length=40, null=True, verbose_name='描述')),
                ('createTime', models.DateTimeField(max_length=0, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(max_length=0, null=True, verbose_name='修改时间')),
                ('deleteTime', models.DateTimeField(max_length=0, null=True, verbose_name='删除时间')),
                ('type', models.IntegerField(default=0, null=True, verbose_name='类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('isDelete', models.IntegerField(default=0, null=True, verbose_name='删除状态')),
                ('isShow', models.IntegerField(default=1, null=True, verbose_name='显示状态')),
                ('create_by', models.CharField(max_length=20, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '文章分类表',
                'verbose_name_plural': '文章分类表',
                'db_table': 'stack_article_classify',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('description', models.CharField(max_length=160, null=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('createTime', models.DateTimeField(max_length=1, null=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(max_length=1, null=True, verbose_name='修改时间')),
                ('deleteTime', models.DateTimeField(max_length=1, null=True, verbose_name='删除时间')),
                ('type', models.IntegerField(default=0, null=True, verbose_name='类型')),
                ('original', models.IntegerField(default=0, null=True, verbose_name='类型')),
                ('views', models.IntegerField(default=0, null=True, verbose_name='预览数')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='排序')),
                ('isDelete', models.IntegerField(default=0, null=True, verbose_name='删除状态')),
                ('isShow', models.IntegerField(default=1, null=True, verbose_name='显示状态')),
                ('check', models.IntegerField(default=2, null=True, verbose_name='审核状态')),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.classify', verbose_name='分类id')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 'stack_article',
            },
        ),
    ]
