# Generated by Django 3.2.4 on 2022-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hotspot',
            field=models.IntegerField(default=0, null=True, verbose_name='热门'),
        ),
    ]
