# Generated by Django 3.2.4 on 2022-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=80, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sort',
            field=models.IntegerField(default=0, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20, verbose_name='文章标题'),
        ),
    ]
