# Generated by Django 3.2.4 on 2022-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220715_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateTimeField(max_length=10, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleteTime',
            field=models.DateTimeField(max_length=10, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updateTime',
            field=models.DateTimeField(max_length=10, null=True, verbose_name='修改时间'),
        ),
    ]
